import type { MDXComponents } from "mdx/types";
import { CaseHeader, CaseStudies } from "@/components/mdx/cases";
import {
  Capability,
  CapabilityList,
  ProcessList,
  ProcessStep,
} from "@/components/mdx/collaborate";
import {
  ActionRow,
  AgentDirective,
  BackLink,
  ChartSection,
  ContactAction,
  ContactRow,
  Eyebrow,
  GhostAction,
  HeaderAction,
  HomeSection,
  HomeTitle,
  Intro,
  MdxAnchor,
  MdxBlockquote,
  MdxHeading2,
  MdxHeading3,
  MdxListItem,
  MdxOrderedList,
  MdxParagraph,
  MdxTable,
  MdxTableBody,
  MdxTableCell,
  MdxTableHead,
  MdxTableHeading,
  MdxTableRow,
  MdxUnorderedList,
  PageHeader,
  PageTitle,
  PrimaryAction,
  ProofAction,
  ProofPanel,
  Section,
} from "@/components/mdx/content";
import { ArchitectureDiagram } from "@/components/mdx/diagram";
import {
  GrowthChart,
  GrowthResults,
  ReferralChart,
} from "@/components/mdx/growth";
import { GitHubActivity, ProfileGallery } from "@/components/mdx/home";
import { Education, Experience, ExperienceList } from "@/components/mdx/work";

const portfolioMdxComponents = {
  ActionRow,
  AgentDirective,
  ArchitectureDiagram,
  a: MdxAnchor,
  BackLink,
  blockquote: MdxBlockquote,
  Capability,
  CapabilityList,
  CaseHeader,
  CaseStudies,
  ChartSection,
  ContactAction,
  ContactRow,
  Education,
  Experience,
  ExperienceList,
  Eyebrow,
  GhostAction,
  GitHubActivity,
  GrowthChart,
  GrowthResults,
  HeaderAction,
  HomeSection,
  HomeTitle,
  h2: MdxHeading2,
  h3: MdxHeading3,
  Intro,
  li: MdxListItem,
  ol: MdxOrderedList,
  PageHeader,
  PageTitle,
  PrimaryAction,
  ProcessList,
  ProcessStep,
  ProfileGallery,
  ProofAction,
  ProofPanel,
  p: MdxParagraph,
  ReferralChart,
  Section,
  table: MdxTable,
  tbody: MdxTableBody,
  td: MdxTableCell,
  th: MdxTableHeading,
  thead: MdxTableHead,
  tr: MdxTableRow,
  ul: MdxUnorderedList,
} satisfies MDXComponents;

export function useMDXComponents(components: MDXComponents): MDXComponents {
  return {
    ...portfolioMdxComponents,
    ...components,
  };
}
